### ISSUE TITLE
captchaElemPrefix interfering with invisible reCaptcha execute call

### ISSUE THREAD

**Issue by rdrenker** [Enngage/ngx-captcha#12] opened 2018-07-16 21:36 UTC
When calling the execute method on the InvisibleReCaptchaComponent, I am getting the following error:

`ERROR Error: Invalid site key or not loaded in api.js: ngx_captcha_id_
    at Object.Qs [as execute] (recaptcha__en.js:formatted:12496)
    at InvisibleReCaptchaComponent.push../node_modules/ngx-captcha/fesm5/ngx-captcha.js.InvisibleReCaptchaComponent.execute (ngx-captcha.js:637)
    at LoginComponent.push../src/app/features/login/login.component.ts.LoginComponent.login (login.component.ts:52)`

When stepping into the execute call, I see that it is calling...
`
 this.reCaptchaApi.execute(this.captchaElemPrefix);
`
... which is passing in the "ngx_captcha_id_" value as the "optional widget ID" parameter into the Google API.

Upon stepping into the Google API, its throwing an error while attempting to locate the index of this particular reCaptcha widget within whatever "__grecaptcha_cfg.qd" is;  in my tests, "qd" always returns an empty object, which then results in Google throwing the above error; ie:

![image](https://user-images.githubusercontent.com/645718/42784521-20c9687a-8915-11e8-89d5-4a65b0540969.png)

If I force the "captchaElemPrefix" to be undefined, then the Google API falls back to looking for the first widget, and then everything works properly.

By tossing the following "handleLoad" code in place, I'm able to get past this issue:

```
    handleLoad() {
        (<any>this.captchaElem).captchaElemPrefix = undefined;
    }

```

However this feels very hacky..  I'm wondering if there is some type of init / setup call that is being missed which would properly populate this "qd" object, such that passing in the widget ID would work?

Also note that this is directly reproducible in the demo app (just downloaded it and tried to hit "execute", ie:

![image](https://user-images.githubusercontent.com/645718/42784955-5b1c5ac2-8916-11e8-981f-4e75b1594101.png)

**Comment by Enngage** [comment] 2018-07-17 06:03
Thanks a lot for letting me know & great description! It was indeed a bug caused by me during the last refactor. The execute method should be called with `id` that is retrieved from Google when creating new captcha. Fix was as easy as to change the method to:

```
 execute(): void {
    this.reCaptchaApi.execute(this.captchaId);
  }
```
Should be fixed in latest release `3.1.1`. Thanks again!

**Closed** 2018-07-18 06:34 UTC
Labels: bug

**Comment by Enngage** [comment] 2018-12-21 14:32
Hi, this issue is now fixed and closed. If you see this issue, maybe you just have wrong site key? 

If you feel this is an issue, please provide a stackblitz demo or proper description.

**Comment by samiullahkhalid4** [comment] 2018-12-21 15:02
@Enngage Hi I have read the article this issue is in the latest version of the contact form 7. now i have downgrade my contact form 7 version 5.1 to 4.9.2 and now am seeing this error 
I have re-generate the keys two more times but still this issue.
![image](https://user-images.githubusercontent.com/39240797/50348650-3b814080-055b-11e9-91b6-d2e47dd0c850.png)

**Comment by samiullahkhalid4** [comment] 2018-12-21 15:10
@rdrenker @rdrenker 
I have fixed the issue after downgraded the contact form 7 plugin and use the Google Recaptcha Plugin V2 instead of V3.
This Error Showing by the V3 Error for site owner: etc ....
Use the version 2 of the Captcha and contact form version i ussing now 4.9.2.
It's working fine for me now .
Thanks!

**Comment by Enngage** [comment] 2018-12-21 15:14
This is not the solution. Please be sure to review Google's documentation on Captcha and setup your site keys & domains correctly. This should be your starting point: https://developers.google.com/recaptcha/intro

**Comment by samiullahkhalid4** [comment] 2018-12-21 18:09
Thank You!
